apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::900880114779:role/eksctl-eksctl-demo-nodegroup-ng-64-NodeInstanceRole-hbkusV2jiWxL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::900880114779:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::900880114779:role/eksctl-eksctl-demo-nodegroup-ng-64-NodeInstanceRole-hbkusV2jiWxL\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::900880114779:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-07-29T08:52:18Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1237","uid":"a3917acf-2af7-4d47-8f94-8a9bf5db9cee"}}
  creationTimestamp: "2024-07-29T08:52:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5585"
  uid: a3917acf-2af7-4d47-8f94-8a9bf5db9cee
